name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      - name: Generate Android platform files
        run: |
          cp lib/main.dart /tmp/main.dart.bak
          flutter create --project-name negocio_app --org com.minegocio --platforms=android .
          cp /tmp/main.dart.bak lib/main.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: negocio-apk
          path: build/app/outputs/flutter-apk/app-release.apk
